import { type Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "@/components/ui/sonner";

import { Lato } from "next/font/google";
import "./globals.css";

const font = Lato({
  weight: ["100", "300", "400", "700", "900"],
  style: "normal",
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "Clerk Next.js Quickstart",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en" className={font.className}>
      <body>
        {children}
        <Toaster position="bottom-center" richColors /> {/* ✅ This enables the popups */}
      </body>

      </html>
    </ClerkProvider>
  );
}
